#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Carvino.Editor
{
    public static class HatchPlayableImportValidation
    {
        [MenuItem("Carvino/Validation/Validate Staged Playable Hatch")]
        public static void ValidateStaged()
        {
            Validate(HatchPlayableModelPostprocessor.StagedPath, "CARVINO_HATCH_STAGED_VALID");
        }

        [MenuItem("Carvino/Validation/Validate Integrated Playable Hatch")]
        public static void ValidateIntegrated()
        {
            Validate(HatchPlayableModelPostprocessor.GameplayPath, "CARVINO_HATCH_INTEGRATED_VALID");
            ValidateSceneInstances();
        }

        private static void Validate(string path, string successMarker)
        {
            AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceSynchronousImport | ImportAssetOptions.ForceUpdate);
            GameObject model = AssetDatabase.LoadAssetAtPath<GameObject>(path);
            Require(model != null, "Playable hatch model could not be loaded: " + path);
            GameObject instance = UnityEngine.Object.Instantiate(model);
            instance.hideFlags = HideFlags.HideAndDontSave;
            try
            {
                Transform lod0 = FindRecursive(instance.transform, "LOD0");
                Transform lod1 = FindRecursive(instance.transform, "LOD1");
                Transform lod2 = FindRecursive(instance.transform, "LOD2");
                Require(lod0 != null && lod1 != null && lod2 != null, "LOD0/LOD1/LOD2 hierarchy is incomplete.");

                LODGroup group = instance.GetComponent<LODGroup>();
                Require(group != null, "LODGroup was not generated by the model importer.");
                Require(group.GetLODs().Length == 3, "Expected exactly three LOD levels.");

                int[] counts = { CountTriangles(lod0), CountTriangles(lod1), CountTriangles(lod2) };
                Require(counts[0] >= 120000 && counts[0] <= 180000, "LOD0 triangle budget failed: " + counts[0]);
                Require(counts[1] >= 45000 && counts[1] <= 80000, "LOD1 triangle budget failed: " + counts[1]);
                Require(counts[2] >= 20000 && counts[2] <= 40000, "LOD2 triangle budget failed: " + counts[2]);

                foreach (string wheel in new[] { "Wheel_FL", "Wheel_FR", "Wheel_RL", "Wheel_RR" })
                {
                    Transform wheelRoot = FindRecursive(lod0, wheel);
                    Require(wheelRoot != null, "Gameplay wheel root missing: " + wheel);
                }

                HashSet<string> materialGroups = new HashSet<string>(StringComparer.Ordinal);
                foreach (Renderer renderer in lod0.GetComponentsInChildren<Renderer>(true))
                {
                    foreach (Material material in renderer.sharedMaterials)
                    {
                        if (material == null) continue;
                        if (material.name.StartsWith("CARVINO_Hatch_Body_4K__", StringComparison.Ordinal)) materialGroups.Add("Body");
                        if (material.name.StartsWith("CARVINO_Hatch_Interior_4K__", StringComparison.Ordinal)) materialGroups.Add("Interior");
                        if (material.name.StartsWith("CARVINO_Hatch_Mechanical_4K__", StringComparison.Ordinal)) materialGroups.Add("Mechanical");
                        if (material.name.StartsWith("CARVINO_Hatch_GlassLights_4K__", StringComparison.Ordinal)) materialGroups.Add("GlassLights");
                    }
                }
                Require(materialGroups.Count == 4, "Expected four 4K-ready material groups; found " + string.Join(", ", materialGroups));

                Bounds bounds = RendererBounds(lod0);
                // The original asset was authored in a Y-up Blender scene and its
                // existing FBX import carries Unity's axis-conversion transform.
                // Compatibility is measured against that shipping model layout so
                // every saved scene keeps the same camera framing and forward axis.
                Vector3 expected = path.Equals(HatchPlayableModelPostprocessor.StagedPath, StringComparison.OrdinalIgnoreCase)
                    ? LegacyGameplayBounds()
                    : new Vector3(2.1643f, 4.2820f, 1.2787f);
                Require(Mathf.Abs(bounds.size.x - expected.x) < 0.18f, "Unexpected imported bounds X: " + bounds.size.x);
                Require(Mathf.Abs(bounds.size.y - expected.y) < 0.22f, "Unexpected imported bounds Y: " + bounds.size.y);
                Require(Mathf.Abs(bounds.size.z - expected.z) < 0.18f, "Unexpected imported bounds Z: " + bounds.size.z);

                Debug.Log(successMarker + " path=" + path + " tris=" + string.Join("/", counts) +
                          " bounds=" + bounds.size.ToString("F3") + " wheelRoots=4 materialGroups=4");
            }
            finally
            {
                UnityEngine.Object.DestroyImmediate(instance);
            }
        }

        private static int CountTriangles(Transform root)
        {
            int total = 0;
            foreach (MeshFilter filter in root.GetComponentsInChildren<MeshFilter>(true))
            {
                Mesh mesh = filter.sharedMesh;
                if (mesh == null) continue;
                for (int index = 0; index < mesh.subMeshCount; index++)
                    total += (int)mesh.GetIndexCount(index) / 3;
            }
            return total;
        }

        private static Bounds RendererBounds(Transform root)
        {
            Renderer[] renderers = root.GetComponentsInChildren<Renderer>(true);
            Require(renderers.Length > 0, "LOD0 has no renderers.");
            Bounds bounds = renderers[0].bounds;
            for (int index = 1; index < renderers.Length; index++) bounds.Encapsulate(renderers[index].bounds);
            return bounds;
        }

        private static Vector3 LegacyGameplayBounds()
        {
            GameObject legacy = AssetDatabase.LoadAssetAtPath<GameObject>(HatchPlayableModelPostprocessor.GameplayPath);
            Require(legacy != null, "Legacy gameplay hatch is unavailable for compatibility comparison.");
            GameObject instance = UnityEngine.Object.Instantiate(legacy);
            instance.hideFlags = HideFlags.HideAndDontSave;
            try
            {
                Renderer[] renderers = instance.GetComponentsInChildren<Renderer>(true);
                Require(renderers.Length > 0, "Legacy gameplay hatch has no renderers.");
                Bounds bounds = renderers[0].bounds;
                for (int index = 1; index < renderers.Length; index++) bounds.Encapsulate(renderers[index].bounds);
                return bounds.size;
            }
            finally
            {
                UnityEngine.Object.DestroyImmediate(instance);
            }
        }

        private static Transform FindRecursive(Transform parent, string name)
        {
            if (parent.name == name) return parent;
            for (int index = 0; index < parent.childCount; index++)
            {
                Transform found = FindRecursive(parent.GetChild(index), name);
                if (found != null) return found;
            }
            return null;
        }

        private static void ValidateSceneInstances()
        {
            (string path, string instanceName)[] checks =
            {
                ("Assets/Carvino/Scenes/MainMenu.unity", "Menu Hatch"),
                ("Assets/Carvino/Scenes/Career.unity", "Career Hatch"),
                ("Assets/Carvino/Scenes/Garage.unity", "Garage Hatch"),
                ("Assets/Carvino/Scenes/RaceDay.unity", "Race Day Hatch"),
                ("Assets/Carvino/Scenes/QuarterMilePrototype.unity", "Player Hatch")
            };
            SceneSetup[] setup = EditorSceneManager.GetSceneManagerSetup();
            try
            {
                foreach ((string path, string instanceName) in checks)
                {
                    Scene scene = EditorSceneManager.OpenScene(path, OpenSceneMode.Single);
                    Transform instance = null;
                    foreach (GameObject sceneRoot in scene.GetRootGameObjects())
                    {
                        instance = FindRecursive(sceneRoot.transform, instanceName);
                        if (instance != null) break;
                    }
                    Require(instance != null, "Hatch instance missing from scene: " + path);
                    LODGroup group = instance.GetComponent<LODGroup>();
                    if (group == null) group = instance.GetComponentInChildren<LODGroup>(true);
                    Require(group != null && group.GetLODs().Length == 3, "Playable hatch LODGroup missing in scene: " + path);
                    Require(instance.GetComponentsInChildren<MeshFilter>(true).Length > 0, "Playable hatch meshes missing in scene: " + path);
                    Debug.Log("CARVINO_HATCH_SCENE_VALID path=" + path + " instance=" + instanceName + " lods=3");
                }
            }
            finally
            {
                bool hasLoadedScene = false;
                foreach (SceneSetup item in setup) hasLoadedScene |= item.isLoaded;
                if (hasLoadedScene) EditorSceneManager.RestoreSceneManagerSetup(setup);
            }
        }

        private static void Require(bool condition, string message)
        {
            if (!condition) throw new InvalidOperationException(message);
        }
    }
}
#endif
